version: '3.8'

services:
  backend:
    build:
      context: ./spearback
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    env_file:
      - .env  
    restart: unless-stopped

  frontend:
    build:
      context: ./spear6
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    restart: unless-stopped